// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-s3"
	"github.com/aws/aws-sdk-go/service/s3"
	"sync"
)

var (
	lockS3SDKClientMockCompleteMultipartUpload sync.RWMutex
	lockS3SDKClientMockCreateMultipartUpload   sync.RWMutex
	lockS3SDKClientMockGetObject               sync.RWMutex
	lockS3SDKClientMockListMultipartUploads    sync.RWMutex
	lockS3SDKClientMockListObjectsV2           sync.RWMutex
	lockS3SDKClientMockListParts               sync.RWMutex
	lockS3SDKClientMockUploadPart              sync.RWMutex
)

// Ensure, that S3SDKClientMock does implement s3client.S3SDKClient.
// If this is not the case, regenerate this file with moq.
var _ s3client.S3SDKClient = &S3SDKClientMock{}

// S3SDKClientMock is a mock implementation of s3client.S3SDKClient.
//
//     func TestSomethingThatUsesS3SDKClient(t *testing.T) {
//
//         // make and configure a mocked s3client.S3SDKClient
//         mockedS3SDKClient := &S3SDKClientMock{
//             CompleteMultipartUploadFunc: func(input *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error) {
// 	               panic("mock out the CompleteMultipartUpload method")
//             },
//             CreateMultipartUploadFunc: func(in1 *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error) {
// 	               panic("mock out the CreateMultipartUpload method")
//             },
//             GetObjectFunc: func(input *s3.GetObjectInput) (*s3.GetObjectOutput, error) {
// 	               panic("mock out the GetObject method")
//             },
//             ListMultipartUploadsFunc: func(in1 *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error) {
// 	               panic("mock out the ListMultipartUploads method")
//             },
//             ListObjectsV2Func: func(input *s3.ListObjectsV2Input) (*s3.ListObjectsV2Output, error) {
// 	               panic("mock out the ListObjectsV2 method")
//             },
//             ListPartsFunc: func(in1 *s3.ListPartsInput) (*s3.ListPartsOutput, error) {
// 	               panic("mock out the ListParts method")
//             },
//             UploadPartFunc: func(in1 *s3.UploadPartInput) (*s3.UploadPartOutput, error) {
// 	               panic("mock out the UploadPart method")
//             },
//         }
//
//         // use mockedS3SDKClient in code that requires s3client.S3SDKClient
//         // and then make assertions.
//
//     }
type S3SDKClientMock struct {
	// CompleteMultipartUploadFunc mocks the CompleteMultipartUpload method.
	CompleteMultipartUploadFunc func(input *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error)

	// CreateMultipartUploadFunc mocks the CreateMultipartUpload method.
	CreateMultipartUploadFunc func(in1 *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error)

	// GetObjectFunc mocks the GetObject method.
	GetObjectFunc func(input *s3.GetObjectInput) (*s3.GetObjectOutput, error)

	// ListMultipartUploadsFunc mocks the ListMultipartUploads method.
	ListMultipartUploadsFunc func(in1 *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error)

	// ListObjectsV2Func mocks the ListObjectsV2 method.
	ListObjectsV2Func func(input *s3.ListObjectsV2Input) (*s3.ListObjectsV2Output, error)

	// ListPartsFunc mocks the ListParts method.
	ListPartsFunc func(in1 *s3.ListPartsInput) (*s3.ListPartsOutput, error)

	// UploadPartFunc mocks the UploadPart method.
	UploadPartFunc func(in1 *s3.UploadPartInput) (*s3.UploadPartOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// CompleteMultipartUpload holds details about calls to the CompleteMultipartUpload method.
		CompleteMultipartUpload []struct {
			// Input is the input argument value.
			Input *s3.CompleteMultipartUploadInput
		}
		// CreateMultipartUpload holds details about calls to the CreateMultipartUpload method.
		CreateMultipartUpload []struct {
			// In1 is the in1 argument value.
			In1 *s3.CreateMultipartUploadInput
		}
		// GetObject holds details about calls to the GetObject method.
		GetObject []struct {
			// Input is the input argument value.
			Input *s3.GetObjectInput
		}
		// ListMultipartUploads holds details about calls to the ListMultipartUploads method.
		ListMultipartUploads []struct {
			// In1 is the in1 argument value.
			In1 *s3.ListMultipartUploadsInput
		}
		// ListObjectsV2 holds details about calls to the ListObjectsV2 method.
		ListObjectsV2 []struct {
			// Input is the input argument value.
			Input *s3.ListObjectsV2Input
		}
		// ListParts holds details about calls to the ListParts method.
		ListParts []struct {
			// In1 is the in1 argument value.
			In1 *s3.ListPartsInput
		}
		// UploadPart holds details about calls to the UploadPart method.
		UploadPart []struct {
			// In1 is the in1 argument value.
			In1 *s3.UploadPartInput
		}
	}
}

// CompleteMultipartUpload calls CompleteMultipartUploadFunc.
func (mock *S3SDKClientMock) CompleteMultipartUpload(input *s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error) {
	if mock.CompleteMultipartUploadFunc == nil {
		panic("S3SDKClientMock.CompleteMultipartUploadFunc: method is nil but S3SDKClient.CompleteMultipartUpload was just called")
	}
	callInfo := struct {
		Input *s3.CompleteMultipartUploadInput
	}{
		Input: input,
	}
	lockS3SDKClientMockCompleteMultipartUpload.Lock()
	mock.calls.CompleteMultipartUpload = append(mock.calls.CompleteMultipartUpload, callInfo)
	lockS3SDKClientMockCompleteMultipartUpload.Unlock()
	return mock.CompleteMultipartUploadFunc(input)
}

// CompleteMultipartUploadCalls gets all the calls that were made to CompleteMultipartUpload.
// Check the length with:
//     len(mockedS3SDKClient.CompleteMultipartUploadCalls())
func (mock *S3SDKClientMock) CompleteMultipartUploadCalls() []struct {
	Input *s3.CompleteMultipartUploadInput
} {
	var calls []struct {
		Input *s3.CompleteMultipartUploadInput
	}
	lockS3SDKClientMockCompleteMultipartUpload.RLock()
	calls = mock.calls.CompleteMultipartUpload
	lockS3SDKClientMockCompleteMultipartUpload.RUnlock()
	return calls
}

// CreateMultipartUpload calls CreateMultipartUploadFunc.
func (mock *S3SDKClientMock) CreateMultipartUpload(in1 *s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error) {
	if mock.CreateMultipartUploadFunc == nil {
		panic("S3SDKClientMock.CreateMultipartUploadFunc: method is nil but S3SDKClient.CreateMultipartUpload was just called")
	}
	callInfo := struct {
		In1 *s3.CreateMultipartUploadInput
	}{
		In1: in1,
	}
	lockS3SDKClientMockCreateMultipartUpload.Lock()
	mock.calls.CreateMultipartUpload = append(mock.calls.CreateMultipartUpload, callInfo)
	lockS3SDKClientMockCreateMultipartUpload.Unlock()
	return mock.CreateMultipartUploadFunc(in1)
}

// CreateMultipartUploadCalls gets all the calls that were made to CreateMultipartUpload.
// Check the length with:
//     len(mockedS3SDKClient.CreateMultipartUploadCalls())
func (mock *S3SDKClientMock) CreateMultipartUploadCalls() []struct {
	In1 *s3.CreateMultipartUploadInput
} {
	var calls []struct {
		In1 *s3.CreateMultipartUploadInput
	}
	lockS3SDKClientMockCreateMultipartUpload.RLock()
	calls = mock.calls.CreateMultipartUpload
	lockS3SDKClientMockCreateMultipartUpload.RUnlock()
	return calls
}

// GetObject calls GetObjectFunc.
func (mock *S3SDKClientMock) GetObject(input *s3.GetObjectInput) (*s3.GetObjectOutput, error) {
	if mock.GetObjectFunc == nil {
		panic("S3SDKClientMock.GetObjectFunc: method is nil but S3SDKClient.GetObject was just called")
	}
	callInfo := struct {
		Input *s3.GetObjectInput
	}{
		Input: input,
	}
	lockS3SDKClientMockGetObject.Lock()
	mock.calls.GetObject = append(mock.calls.GetObject, callInfo)
	lockS3SDKClientMockGetObject.Unlock()
	return mock.GetObjectFunc(input)
}

// GetObjectCalls gets all the calls that were made to GetObject.
// Check the length with:
//     len(mockedS3SDKClient.GetObjectCalls())
func (mock *S3SDKClientMock) GetObjectCalls() []struct {
	Input *s3.GetObjectInput
} {
	var calls []struct {
		Input *s3.GetObjectInput
	}
	lockS3SDKClientMockGetObject.RLock()
	calls = mock.calls.GetObject
	lockS3SDKClientMockGetObject.RUnlock()
	return calls
}

// ListMultipartUploads calls ListMultipartUploadsFunc.
func (mock *S3SDKClientMock) ListMultipartUploads(in1 *s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error) {
	if mock.ListMultipartUploadsFunc == nil {
		panic("S3SDKClientMock.ListMultipartUploadsFunc: method is nil but S3SDKClient.ListMultipartUploads was just called")
	}
	callInfo := struct {
		In1 *s3.ListMultipartUploadsInput
	}{
		In1: in1,
	}
	lockS3SDKClientMockListMultipartUploads.Lock()
	mock.calls.ListMultipartUploads = append(mock.calls.ListMultipartUploads, callInfo)
	lockS3SDKClientMockListMultipartUploads.Unlock()
	return mock.ListMultipartUploadsFunc(in1)
}

// ListMultipartUploadsCalls gets all the calls that were made to ListMultipartUploads.
// Check the length with:
//     len(mockedS3SDKClient.ListMultipartUploadsCalls())
func (mock *S3SDKClientMock) ListMultipartUploadsCalls() []struct {
	In1 *s3.ListMultipartUploadsInput
} {
	var calls []struct {
		In1 *s3.ListMultipartUploadsInput
	}
	lockS3SDKClientMockListMultipartUploads.RLock()
	calls = mock.calls.ListMultipartUploads
	lockS3SDKClientMockListMultipartUploads.RUnlock()
	return calls
}

// ListObjectsV2 calls ListObjectsV2Func.
func (mock *S3SDKClientMock) ListObjectsV2(input *s3.ListObjectsV2Input) (*s3.ListObjectsV2Output, error) {
	if mock.ListObjectsV2Func == nil {
		panic("S3SDKClientMock.ListObjectsV2Func: method is nil but S3SDKClient.ListObjectsV2 was just called")
	}
	callInfo := struct {
		Input *s3.ListObjectsV2Input
	}{
		Input: input,
	}
	lockS3SDKClientMockListObjectsV2.Lock()
	mock.calls.ListObjectsV2 = append(mock.calls.ListObjectsV2, callInfo)
	lockS3SDKClientMockListObjectsV2.Unlock()
	return mock.ListObjectsV2Func(input)
}

// ListObjectsV2Calls gets all the calls that were made to ListObjectsV2.
// Check the length with:
//     len(mockedS3SDKClient.ListObjectsV2Calls())
func (mock *S3SDKClientMock) ListObjectsV2Calls() []struct {
	Input *s3.ListObjectsV2Input
} {
	var calls []struct {
		Input *s3.ListObjectsV2Input
	}
	lockS3SDKClientMockListObjectsV2.RLock()
	calls = mock.calls.ListObjectsV2
	lockS3SDKClientMockListObjectsV2.RUnlock()
	return calls
}

// ListParts calls ListPartsFunc.
func (mock *S3SDKClientMock) ListParts(in1 *s3.ListPartsInput) (*s3.ListPartsOutput, error) {
	if mock.ListPartsFunc == nil {
		panic("S3SDKClientMock.ListPartsFunc: method is nil but S3SDKClient.ListParts was just called")
	}
	callInfo := struct {
		In1 *s3.ListPartsInput
	}{
		In1: in1,
	}
	lockS3SDKClientMockListParts.Lock()
	mock.calls.ListParts = append(mock.calls.ListParts, callInfo)
	lockS3SDKClientMockListParts.Unlock()
	return mock.ListPartsFunc(in1)
}

// ListPartsCalls gets all the calls that were made to ListParts.
// Check the length with:
//     len(mockedS3SDKClient.ListPartsCalls())
func (mock *S3SDKClientMock) ListPartsCalls() []struct {
	In1 *s3.ListPartsInput
} {
	var calls []struct {
		In1 *s3.ListPartsInput
	}
	lockS3SDKClientMockListParts.RLock()
	calls = mock.calls.ListParts
	lockS3SDKClientMockListParts.RUnlock()
	return calls
}

// UploadPart calls UploadPartFunc.
func (mock *S3SDKClientMock) UploadPart(in1 *s3.UploadPartInput) (*s3.UploadPartOutput, error) {
	if mock.UploadPartFunc == nil {
		panic("S3SDKClientMock.UploadPartFunc: method is nil but S3SDKClient.UploadPart was just called")
	}
	callInfo := struct {
		In1 *s3.UploadPartInput
	}{
		In1: in1,
	}
	lockS3SDKClientMockUploadPart.Lock()
	mock.calls.UploadPart = append(mock.calls.UploadPart, callInfo)
	lockS3SDKClientMockUploadPart.Unlock()
	return mock.UploadPartFunc(in1)
}

// UploadPartCalls gets all the calls that were made to UploadPart.
// Check the length with:
//     len(mockedS3SDKClient.UploadPartCalls())
func (mock *S3SDKClientMock) UploadPartCalls() []struct {
	In1 *s3.UploadPartInput
} {
	var calls []struct {
		In1 *s3.UploadPartInput
	}
	lockS3SDKClientMockUploadPart.RLock()
	calls = mock.calls.UploadPart
	lockS3SDKClientMockUploadPart.RUnlock()
	return calls
}
